# Generated by Django 4.1.4 on 2022-12-28 13:11

import Restaurant.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Restaurant.models.getfilename)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('list_image', models.ImageField(blank=True, null=True, upload_to=Restaurant.models.getfilename)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('status', models.BooleanField(default=False, help_text='0-show0,1-hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.menu')),
            ],
        ),
    ]
