# Generated by Django 4.1.4 on 2022-12-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_favourite_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='User',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
